### PR TITLE
metrics update: removed unused field, added number of references in paper

### PR DESCRIPTION
**Pull request by ehenneken**
metrics database: The citation histogram for individual papers isn't used, so it was removed. The number of references in a paper has been added. The SQLAlchemy data model was updated as well.

### CODE REVIEW

**Comment by jonnybazookatone** [comment]
You should update the corresponding tests for your changes, just deleting the expected hist data should suffice.

**Comment by ehenneken** [comment]
A drop in coveralls is a failure?

**Comment by jonnybazookatone** [comment]
You can change the level at which you accept the coverage to be green/yellow/red. Travis passes and is green. It must do an AND on the coveralls and travis to give the overall failed/success of the PR. Feel free to change the coverage level requirement for ADS data in the coveralls dashboard.

**Comment by jonnybazookatone** [comment]
FYI; I changed it to 50% (below it fails) and it fails if it drops by 5% from the previous commit.

**Comment by ehenneken** [comment]
Coveralls is rechecked automatically?

**Comment by jonnybazookatone** [comment]
No, coveralls has a webhook with TravisCI, so every time you do a build on TravisCI it notifies coveralls, and sends it the coverage results (that are defined in the .travis.yml build file). Maybe if you re-run the build on TravisCI it might rerun coveralls, not sure, I'll give it a try. Otherwise it's not a big deal, if the test passes you can merge and deploy at will.

**Comment by ehenneken** [comment]
I assume I have to deploy on adsx as user 'beer'? I noticed that the repo on adsx is out of sync with the github repo with local changes in `build_docs.py` and `sync_build.sh`. Are those local changes to be pushed to the master in the github repo?

**Comment by jonnybazookatone** [comment]
You can stash the changes and merge, the code base is the same, it just never got pulled on adsx afterwards, sorry.

**Comment by ehenneken** [comment]
FYI: I stashed the local changed, pulled my updates from github and ran `git stash apply` afterwards

**Pull request merged**
